version: '3'
services:
  webhook:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID:$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY:$AWS_SECRET_ACCESS_KEY
    ports:
      - "443:443" 