services:
  earnyearn:
    build:
      context: ./svc/earnyearn
      dockerfile: ./Dockerfile
    volumes:
      - ./svc/earnyearn/:/app/
    environment:
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - TRADINGVIEW_SECRET=${TRADINGVIEW_SECRET:-asdf}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - EARNYEARN_ORDER_ENDPOINT=${EARNYEARN_ORDER_ENDPOINT:-https://signalspit.dev.alpaca.gigakitty.com/market}
  signalspit:
    build:
      context: ./svc/signalspit
      dockerfile: ./Dockerfile
    volumes:
      - ./svc/signalspit/:/app/
    environment:
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - NGROK_ENABLED=${NGROK_ENABLED:-True}
      - NGROK_DOMAIN=${NGROK_DOMAIN}
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - TRADINGVIEW_SECRET=${TRADINGVIEW_SECRET:-asdf}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
  #  sentimentsheperd:
  #    build:
  #      context: ./svc/sentimentsheperd
  #      dockerfile: ./Dockerfile
  #    volumes:
  #      - ./svc/sentimentsheperd/:/app/
  #    environment:
  #      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  #      - AWS_REGION=${AWS_REGION:-us-east-1}
  #      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
  #      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
  #      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
  #      - ENVIRONMENT=${ENVIRONMENT:-dev}
  #      - OPENAI_API_KEY=${OPENAI_API_KEY:-asdf}
  purrstream:
    build:
      context: ./svc/purrstream
      dockerfile: ./Dockerfile
    ports:
      - 8765:8765
    volumes:
      - ./svc/purrstream/:/app/
    environment:
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
