version: '3'
services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    # runtime: nvidia
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    volumes:
      - $PWD/app/:/app/
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_REGION=us-west-2
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - ENVIRONMENT=${ENVIRONMENT:-dev}
    ports:
      - "5000:5000" 
