version: "3"
services:
  earnyearn:
    build:
      context: ./svc/earnyearn
      dockerfile: ./Dockerfile
    volumes:
      - ./svc/earnyearn/:/app/
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - TRADINGVIEW_SECRET=${TRADINGVIEW_SECRET:-asasdfaskdjfnm90890098kjlkjioweoik}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
  signalspit:
    build:
      context: ./svc/signalspit
      dockerfile: ./Dockerfile
    volumes:
      - ./svc/signalspit/:/app/
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - ENVIRONMENT=${ENVIRONMENT:-dev}
