root_directory: data
listen_port: 5993
grpc_listen_port: 5995
log_level: info
stop_grace_period: 0
wal_rotate_interval: 5
stale_threshold: 5
timezone: "UTC"
utilities_url: "localhost:5994"

triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      destinations:
        - 5Min
        - 15Min
        - 1H
        - 1D

  - module: stream.so
    on: "*/*/*"
    config:
      filter: nasdaq

# bgworkers:
#   - module: gdaxfeeder.so
#     config:
#       base_timeframe: '1Min'
#       query_start: '2018-01-01 00:00'
#       symbols:
#         - BTC-USD
#         - ETH-USD
#         - LTC-USD
#         - BCH-USD
#         - ZRX-USD
#         - ETC-USD
#         - BAT-USD
