root_directory: data
listen_port: 5993
grpc_listen_port: 5995
log_level: info
stop_grace_period: 0
wal_rotate_interval: 5
stale_threshold: 5
timezone: "UTC"
utilities_url: "localhost:5994"

triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      destinations:
        - 5Min
        - 15Min
        - 1H
        - 1D

  - module: stream.so
    on: "*/*/*"
    config:
      filter: nasdaq
#@TODO: get this tested
# bgworkers:
#   - module: alpaca.so
#     config:
#       api_key: your_alpaca_key_id
#       api_secret: your_alpaca_secret
#       ws_server: wss://data.alpaca.markets/stream
#       ws_worker_count: 10
#       feed: alpacadatav1
#       minute_bar_symbols:
#         - '*'
#       quote_symbols:
#         - VOO
#         - SPY
#       trade_symbols:
#         - AAPL