name: Deploy to AWS

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: us-west-2

      - name: Install AWS Copilot CLI
        run: |
          cd /tmp
          curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot
          sudo mv copilot /usr/local/bin/copilot

      - name: Deploy changed services
        run: |
          changed_services=$(git diff --name-only HEAD HEAD~1 | grep '^svc/' | awk -F/ '{print $2}' | uniq)
          for service in $changed_services; do
            if [ "$GITHUB_REF" == "refs/heads/dev" ]; then
              copilot svc deploy --name $service --env dev
            elif [ "$GITHUB_REF" == "refs/heads/main" ]; then
              copilot svc deploy --name $service --env main
            fi
          done