name: Deploy to AWS

on:
  push:
    branches:
      - dev
      - main
  schedule:
    - cron: '0 11 * * 1-5' # 6 AM EST
    - cron: '0 23 * * 1-5' # 6 PM EST

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to AWS OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: us-west-2

      - name: Install AWS Copilot CLI
        run: |
          cd /tmp
          curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot
          sudo mv copilot /usr/local/bin/copilot

      - name: Deploy changed services
        run: |
          changed_services=$(git diff --name-only HEAD HEAD~1 | grep '^svc/' | awk -F/ '{print $2}' | uniq)
          for service in $changed_services; do
            if [ "$GITHUB_REF" == "refs/heads/dev" ]; then
              copilot svc deploy --name $service --env dev
            elif [ "$GITHUB_REF" == "refs/heads/main" ]; then
              copilot svc deploy --name $service --env main
            fi
          done

      - name: Determine schedule time
        id: time
        run: |
          current_time=$(date -u +"%H")
          echo "::set-output name=hour::$current_time"

      - name: Run morning task
        if: steps.time.outputs.hour == '11'
        run: |
          echo "Running morning scheduled task"
          # Add your morning task commands here

      - name: Run evening task
        if: steps.time.outputs.hour == '23'
        run: |
          echo "Running evening scheduled task"
          # Add your evening task commands here
