# .github/workflows/deploy.yml
name: Deploy to AWS

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: us-west-2
 
      # add step that runs on dev branch only
      - name: Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          copilot svc deploy --name api --env dev

      # add step that runs on main branch only
      - name: Main
        if: github.ref == 'refs/heads/main'
        run: |
          copilot svc deploy --name api --env main